services:
  ftp:
    image: delfer/alpine-ftp-server
    container_name: ironweb_ftp
    restart: unless-stopped
    environment:
      USERS: "ironweb|7a3bd64e6cf770c9a5e9526e|/srv/media|1001|1001 ironwebstatic|204d8cd799c4998c4fde91f8|/srv/static|1002|1002"
      ADDRESS: "72.62.138.200"
      MIN_PORT: "21000"
      MAX_PORT: "21010"
    command:
      - /bin/sh
      - -c
      - "chown -R 1001:1001 /srv/media && chown -R 1002:1002 /srv/static && exec /bin/start_vsftpd.sh"
    ports:
      - "21:21"
      - "21000-21010:21000-21010"
    volumes:
      - ironweb_media:/srv/media
      - ironweb_static:/srv/static
    networks:
      - dokploy-network

networks:
  dokploy-network:
    external: true

volumes:
  ironweb_media:
    external: true
    name: ironweb_media
  ironweb_static:
    external: true
    name: ironweb_static